## Parsing Stage of The Pursuit of Happiness: Exploring the DALI_Data-Anon data
### Logan Chang
### DALI Lab Coding Challenge

In this notebook, I begin to load and parse the DALI_Data-Anon data for my application to the DALI Lab. After pulling the data from the lab's challenges webpage [here](https://github.com/dali-lab/dali-challenges), I put the data into a more manageable format and begin my analysis and modeling.

In [1]:
#imports
import json
import pandas as pd

In [2]:
#open the file
with open('/Users/logan/Desktop/DALI/DALI_Data-Anon.json') as f:
    data = json.load(f)

In [3]:
#make a Pandas DataFrame from the data
df = pd.DataFrame.from_dict(data)
df.head()

,year,gender,heightInches,happiness,stressed,sleepPerNight,socialDinnerPerWeek,alcoholDrinksPerWeek,caffeineRating,affiliated,numOfLanguages,gymPerWeek,hoursOnScreen,phoneType
0,'19,Female,63.0,4,2,7,3.0,4.0,1,1,2,3.0,6.0,iOS
1,'19,Male,71.0,4,5,7,3.0,8.0,6,1,2,4.0,6.0,iOS
2,'19,Female,63.0,4,4,7,3.0,2.0,1,1,1,0.0,9.0,Other
3,'19,Male,70.0,4,5,7,7.0,7.0,8,1,1,3.0,7.0,Android
4,'19,Male,70.0,4,8,7,3.0,3.0,3,1,2,5.0,6.0,iOS

In [4]:
#download the DataFrame as a CSV locally
df.to_csv('/Users/logan/Desktop/DALI/DALI_Data-Anon.csv', index=False)